### ISSUE TITLE
[Feat] Highlight text from current cursor position to jump

### ISSUE THREAD

**Issue by hatunike** [krnik/vscode-jumpy#4]
It'd be sweet if there was an option to hold down a command while jumping that enabled highlighting text between current cursor location and the destination jump.

**Comment by ghost** [comment]
This is the relevant piece of code: https://github.com/krnik/vscode-jumpy/blob/master/src/jumpy/mod.ts#L221
Instead of single point selection it would have to expand the current selection :)

Is `[Shift]` a good modifier key to do so?

**Comment by ghost** [comment]
Update: I did implement this feature and using `[Shift]` is not an option. Mainly because we cannot easily detect whether shift was pressed for numbers. 
We can somehow detect it but then the key is registered as `$` instead of `4` and the marker is not matched. 
We could make a walkaround this by mapping `$` to `4`. Although I'm not sure I want to walk down this path yet :)

Unless there will be an API with some kind of `onKey` event in VSCode this issue is blocked.

**Comment by ghost** [comment]
https://github.com/krnik/vscode-jumpy/commit/de1d75877d2a93cb31315ff3109642585a90fadb  Added a support for the selection expansion via separate shortcut. It's may not be as convenient as something like pressing last key with shift but it's something :]
Default key bindings are `shift+alt+j` for expanding selection to start of the word. `shift+alt+k` for expanding selection to the end of the word.

**Comment by wenfangdu** [comment]
@hatunike This extension is deprecated, please use [Jump](https://marketplace.visualstudio.com/items?itemName=wenfangdu.jump) instead.
